version: "3.3"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=spark
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - /opt/mongodb/data:/data/db/
      - /opt/mongodb/log:/var/log/mongodb/
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]
    
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: spark-base-api
    container_name: spark-base-api
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks:
      - main-network

networks:
  main-network:
    external:
      name: spark-network