version: "3.4"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: ${MONGO_HOSTNAME}
    restart: unless-stopped
    ports:
      - ${MONGO_HOST_PORT}:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ${MONGO_DATA_HOST_PATH}:/data/db/
      - ${MONGO_LOG_HOST_PATH}:/var/log/mongodb/
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]
    
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - ${SERVER_HOST_PORT}:8080
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
    networks:
      - main-network

networks:
  main-network:
    external:
      name: spark-network